Module1 task3
htmlacademy-nodejs/153671-buy-and-sell-3 pull request #2
Opened 2020-02-16 14:02 UTC by hopmen

2020-02-16 21:10 UTC, dean992008 requested changes

2020-02-16 21:10 UTC, dean992008 commented on src/utils.js
> +module.exports.getRandomInt = (min, max) => {
Я бы предложил обьявлять как локальные функции, а потом в конце модулять имполитьвать их как обьект. Например: 
```
module.exports = {
  shuffle,
  getRandomInt
}
```

2020-02-16 21:10 UTC, dean992008 commented on src/service/cli/generate.js
> +const getPictureFileName = (number) => number > 10 ? `item${number}.jpg` : `item0${number}.jpg`;
Я бы предложил заменить тернарный оператор на следующую строку: `item${(`0`+number).slice(-2)}.jpg`

2020-02-16 21:10 UTC, dean992008 commented on src/service/cli/generate.js
> +    type: Object.keys(OfferType)[Math.floor(Math.random() * Object.keys(OfferType).length)],
`Math.floor(Math.random() * Object.keys(OfferType).length)` - Возможно это стоит заменить на `getRandomInt`

2020-02-16 21:10 UTC, dean992008 commented on src/service/cli/generate.js
> +    console.log(process.argv);
Скорее всего это забыл удалить.

2020-03-04 19:53 UTC, hopmen commented
pull

2020-03-04 20:52 UTC, merged