Module2 task2
htmlacademy-nodejs/153671-buy-and-sell-3 pull request #4
Opened 2020-03-07 19:10 UTC by hopmen

2020-03-07 21:25 UTC, dean992008 requested changes

2020-03-07 21:25 UTC, dean992008 commented on src/service/cli/generate.js
> +    const sentences = await readContent(FILE_SENTENCES_PATH);
Использовать 3 независимых `await` подряд не совсем правильно. В данном случае их лучше заменить на `Promise.all`

2020-03-11 11:44 UTC, hopmen commented on src/service/cli/generate.js
> +    const sentences = await readContent(FILE_SENTENCES_PATH);
> Использовать 3 независимых `await` подряд не совсем правильно. В данном случае их лучше заменить на `Promise.all`
немного не понял, где 3 `await`

2020-03-11 22:16 UTC, dean992008 commented on src/service/cli/generate.js
> +    const sentences = await readContent(FILE_SENTENCES_PATH);
Да. Сейчас будет как: Мы отправим запрос на открытие файла 1  -> получаем результат ->  отправим запрос на открытие файла 2. Promise.all отправит 3 запроса сразу.

2020-03-16 19:33 UTC, merged