module3-task1
htmlacademy-nodejs/153671-buy-and-sell-3 pull request #6
Opened 2020-03-28 18:48 UTC by hopmen

2020-03-29 16:28 UTC, dean992008 requested changes

2020-03-29 16:28 UTC, dean992008 commented on package.json
> +    "nodemon": "^2.0.2"
Версии зависимостей должны быть зафиксированы: 
https://up.htmlacademy.ru/nodejs/3/criteries#b24

2020-03-29 16:28 UTC, dean992008 commented on src/express/index.js
> +const DEFAULT_PORT = 8080;
https://up.htmlacademy.ru/nodejs/3/criteries#b15

2020-03-29 16:28 UTC, dean992008 commented on src/express/index.js
> +app.use(`/offers`, offersRoutes);
Все роуты я бы вынес в отдельный файл `router/index.js`, а здесь написал только `app.use(router)`.

2020-03-29 16:28 UTC, dean992008 commented on src/express/routes/my-routes.js
> +myRoutes.get(`/comments`, (req, res) =>   res.send(`/my/comments`));
Если выполнить `npm test` то выдаст несколько ошибки форматирования, их нужно исправить.

2020-03-29 16:28 UTC, dean992008 commented on src/express/routes/offers-routes.js
> +offersRouter.get(`/category/:id`, (req, res) => res.send(`/offers/category/:id`));
В этом роуте нужно чтобы если мы укажем `.../category/3` то вернуло `/offers/category/3`. Для решения этой задачи можно воспользоваться обьектом `req.params`

2020-03-31 20:03 UTC, hopmen commented on src/express/index.js
> +const DEFAULT_PORT = 8080;
так переменная DEFAULT_PORT после всех require

2020-04-01 11:17 UTC, dean992008 commented on src/express/index.js
> +const DEFAULT_PORT = 8080;
Тут скорее всего я не обратил внимание.

2020-04-01 11:18 UTC, merged